// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import WhatsAppButton from "@/WhatsAppButton/page";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//         <WhatsAppButton /> {/* ✅ hamesha show hoga */}
//       </body>
//     </html>
//   );
// }








// import WhatsAppButton from "@/WhatsAppButton/page";
import Connect from "./Connect/page";
import Education from "./Education/page";
import Footer from "./Footer/page";
import "./globals.css";
import HeroSection from "./HeroSection/page";
import Learning from "./Learning/page";
import Navbar from "./Navbar/page";
import Projects from "./Projects/page";
import Skills from "./Skills/page";
import WhatsAppButton from "./WhatsAppButton/page";

export const metadata = {
  title: "My Portfolio",
  description: "Portfolio with dark mode and sidebar",
};

export default function layout({ children }) {
  return (
    <html lang="en" className="bg-[#1F1F24] 
">
      <body className=" ">
        <Navbar />
        <HeroSection/>
        <Learning/>
        <Education/>
        <Projects/>
        <Skills/>
        <Connect/>
        <Footer/>
        <main className="">{children}</main>
        <WhatsAppButton/> {/* ✅ Always visible */}
      </body>
    </html>
  );
}

















